// Dedicated hand-tracking worker (also importable on the main thread as a
// fallback detector factory). Runs MediaPipe Tasks Vision HandLandmarker
// locally: local WASM + local model, VIDEO mode, CPU delegate, two hands.
//
// Loader compatibility: the bundled MediaPipe loader fetches its Emscripten
// glue (`vision_wasm_internal.js`, a classic script declaring a global
// `ModuleFactory`) with `importScripts()`. In a *module* worker importScripts
// throws a TypeError, after which MediaPipe calls `self.import(url)`. We
// install that hook: it accepts only same-origin loader URLs and dynamically
// imports the build-time ES-module adapter `<loader>.mjs` (generated by
// scripts/prepare-tracking.mjs from the pinned npm loader plus
// `export default ModuleFactory;`), then assigns the export to
// `self.ModuleFactory`. No eval, Function constructor, blob or CDN is used. In a
// classic worker native importScripts works and the hook is simply unused.
//
// Protocol (main -> worker):
//   {type:'init', wasmUrl, modelUrl}
//   {type:'frame', id, bitmap: ImageBitmap (transferred), timestamp}
//   {type:'close'}
// Worker -> main:
//   {type:'ready', delegate}
//   {type:'result', id, result:{landmarks, handedness}, inferenceMs}
//   {type:'error', id?, message, stage}

import { FilesetResolver, HandLandmarker } from '@mediapipe/tasks-vision';

export const LANDMARKER_OPTIONS = Object.freeze({
  runningMode: 'VIDEO',
  numHands: 2,
  minHandDetectionConfidence: 0.5,
  minHandPresenceConfidence: 0.5,
  minTrackingConfidence: 0.5,
});

/**
 * Install the `self.import` bridge MediaPipe uses in module workers. It maps a
 * same-origin classic loader URL to its prebuilt `.mjs` adapter and exposes the
 * adapter's default export as `scope.ModuleFactory`. `importModule` is
 * injectable for deterministic tests; the default is native dynamic import()
 * (`import` is syntax, not a function value, so it cannot be passed directly).
 */
export function installClassicScriptBridge(scope = globalThis, importModule = null) {
  if (!scope || typeof scope.import === 'function') return false;
  scope.import = async (url) => {
    const origin = scope.location?.origin;
    const target = new URL(String(url), scope.location?.href);
    if (!origin || target.origin !== origin) {
      throw new Error(`Refusing to load a non-local tracking script (${target.href}).`);
    }
    const adapterUrl = `${target.href}.mjs`;
    let loaded;
    try {
      loaded = await (importModule ? importModule(adapterUrl) : import(/* @vite-ignore */ adapterUrl));
    } catch (error) {
      throw new Error(`Tracking runtime failed to load (${adapterUrl}: ${error?.message || error}). Run npm run prepare:tracking.`);
    }
    const factory = loaded?.default;
    if (typeof factory !== 'function') throw new Error(`Tracking runtime did not initialise (${adapterUrl} has no ModuleFactory export).`);
    scope.ModuleFactory = factory;
  };
  return true;
}

/** Create a local HandLandmarker. Shared by the worker and the main-thread fallback. */
export async function createHandLandmarker({ wasmUrl, modelUrl }) {
  if (!wasmUrl || !modelUrl) throw new Error('Tracking files are not configured.');
  const fileset = await FilesetResolver.forVisionTasks(String(wasmUrl).replace(/\/+$/, ''));
  return HandLandmarker.createFromOptions(fileset, {
    ...LANDMARKER_OPTIONS,
    baseOptions: { modelAssetPath: String(modelUrl), delegate: 'CPU' },
  });
}

/** Copy only the plain data the main thread needs (structured-clone safe). */
export function serializeResult(result) {
  const landmarks = (result?.landmarks || []).map((hand) =>
    hand.map((lm) => ({ x: lm.x, y: lm.y, z: lm.z || 0 })),
  );
  const handedness = (result?.handedness || result?.handednesses || []).map((cats) =>
    (cats || []).slice(0, 1).map((c) => ({ categoryName: c.categoryName, score: c.score })),
  );
  return { landmarks, handedness };
}

function runWorker(scope) {
  installClassicScriptBridge(scope);
  let landmarker = null;
  let initPromise = null;
  let closed = false;
  let lastTimestamp = -Infinity;

  const post = (message) => {
    if (!closed) scope.postMessage(message);
  };

  const close = () => {
    closed = true;
    try { landmarker?.close(); } catch { /* already closed */ }
    landmarker = null;
  };

  scope.addEventListener('message', async (event) => {
    const data = event.data || {};
    if (data.type === 'init') {
      if (initPromise) return;
      initPromise = createHandLandmarker(data)
        .then((created) => {
          if (closed) { created.close(); return; }
          landmarker = created;
          post({ type: 'ready', delegate: 'CPU' });
        })
        .catch((error) => post({ type: 'error', stage: 'init', message: error?.message || String(error) }));
      return;
    }
    if (data.type === 'frame') {
      const { bitmap, id } = data;
      try {
        if (closed) return;
        if (!landmarker) throw new Error('Tracker is not ready.');
        // VIDEO mode requires strictly increasing timestamps.
        const timestamp = Math.max(Number(data.timestamp) || 0, lastTimestamp + 1);
        lastTimestamp = timestamp;
        const started = performance.now();
        const result = landmarker.detectForVideo(bitmap, timestamp);
        const inferenceMs = performance.now() - started;
        post({ type: 'result', id, result: serializeResult(result), inferenceMs });
      } catch (error) {
        post({ type: 'error', stage: 'frame', id, message: error?.message || String(error) });
      } finally {
        try { bitmap?.close(); } catch { /* already detached */ }
      }
      return;
    }
    if (data.type === 'close') close();
  });
}

const isWorkerScope =
  typeof WorkerGlobalScope !== 'undefined' &&
  typeof self !== 'undefined' &&
  self instanceof WorkerGlobalScope; // eslint-disable-line no-undef

if (isWorkerScope) runWorker(self);
